#pragma once
// Motor Configuration
#define MOTOR_RIGHT_FORWARD D1
#define MOTOR_RIGHT_BACKWARD D2
#define MOTOR_LEFT_FORWARD D3
#define MOTOR_LEFT_BACKWARD D4

// Connection
#define WIFI_AP_SSID_PREFIX "SUMO-"
#define WIFI_AP_PASSWORD "12345678"
#define WIFI_AP_MAX_CONNECTION 1